first = float (input("Enter a number: "))
second = float (input("Enter another number: "))
print("The 2 values added is: ", first + second)
print("The second value subtracted from the first is: ", first - second)
print("The first value multiplide by the second value is: ", first * second)
print("The first value divided by the second value is: ", first / second)
